version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./mounts/proto:/usr/src/app/generated_proto
      - ./mounts/data:/usr/src/app/data
    depends_on:
      - nats-server
      
  #   ports:
  #     - "8000:5000"
  #   volumes:
  #     - .:/code
  #     - logvolume01:/var/log
  #   links:
  #     - redis
  nats-server:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"