version: "3.9"
services:

  engine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: ./cmd/engine
    volumes:
    - ./mounts/data:/usr/src/app/data
    depends_on:
      - nats-server

  handler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: ./cmd/handler
    depends_on:
      - engine
      - nats-server

  nats-server:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    logging:
      driver: none # disable logging

  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - engine

  build_proto:
    build: 
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:80"
    volumes:
      - ./mounts/proto:/usr/src/app/generated_proto
      # - ./mounts/data:/usr/src/app/data
    # depends_on:
    #   - nats-server